"""CLI helper for launchers: check/persist online (relay) mode settings.

Used by run_desktop.bat / run_desktop.sh so the boot-time question is asked
exactly once — the answer is persisted to config.toml, not just the process
environment (VMA_RELAY_URL / VMA_RELAY_REG_TOKEN env vars remain available
as per-run overrides for scripting).

Usage (from the desktop/ directory):

    python -m vma.set_relay --check              exit 0 if relay_url is set
    python -m vma.set_relay --set URL [TOKEN]    persist and exit
    python -m vma.set_relay --wizard             interactive suggestions

The wizard knows this machine can BE the relay host: it detects the LAN
address, suggests tcp://<lan-ip>:8765 with a freshly minted registration
token, explains the reachability trade-offs (same-Wi-Fi now; port-forward
or a public VPS relay for other networks), and can write a relay launcher
script (run_relay.bat / run_relay.sh) so the relay is one double-click away.
"""

from __future__ import annotations

import secrets
import socket
import sys
from pathlib import Path

from .config import load_config

RELAY_PORT = 8765


def relay_configured() -> bool:
    cfg = load_config()
    return bool(cfg.server.relay_url.strip())


def persist(url: str, token: str | None) -> None:
    from .app import save_config_toml  # lazy: avoids FastAPI import for --check

    cfg = load_config()
    cfg.server.relay_url = url.strip()
    if token is not None and token.strip():
        cfg.server.relay_reg_token = token.strip()
    save_config_toml(cfg)


def lan_ip() -> str:
    """Best-effort LAN address (no packets sent; UDP connect = route lookup)."""
    try:
        from .utils import lan_address_candidates

        primary, _ = lan_address_candidates()
        if primary:
            return primary
    except Exception:
        pass
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            sock.connect(("192.168.255.255", 80))
            return sock.getsockname()[0]
        finally:
            sock.close()
    except OSError:
        return "127.0.0.1"


def relay_running_locally(port: int = RELAY_PORT) -> bool:
    """True if something already listens on the relay port (a live relay)."""
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.5):
            return True
    except OSError:
        return False


def write_relay_launcher(repo_root: Path, token: str, port: int = RELAY_PORT) -> Path:
    """One-double-click relay starter next to run_desktop.bat."""
    bat = repo_root / "run_relay.bat"
    bat.write_text(
        "@echo off\r\n"
        "cd /d \"%~dp0relay\"\r\n"
        "echo Starting the VMA relay on port " + str(port) + "\r\n"
        "echo Registration token: " + token + "\r\n"
        "echo Keep this window open while the relay is in use.\r\n"
        "\"..\\desktop\\.venv\\Scripts\\python.exe\" -m vma_relay.server "
        "--host 0.0.0.0 --port " + str(port) + " --reg-token " + token + "\r\n"
        "pause\r\n",
        encoding="utf-8",
    )
    sh = repo_root / "run_relay.sh"
    sh.write_text(
        "#!/usr/bin/env bash\n"
        "# VMA relay launcher (generated by vma.set_relay)\n"
        "set -euo pipefail\n"
        'cd "$(dirname "$0")/relay"\n'
        'exec "../desktop/.venv/bin/python" -m vma_relay.server '
        "--host 0.0.0.0 --port " + str(port) + " --reg-token " + token + "\n",
        encoding="utf-8",
    )
    try:
        sh.chmod(0o755)
    except OSError:
        pass
    return bat


def wizard() -> bool:
    """Interactive, host-aware relay setup. Returns True if configured."""
    ip = lan_ip()
    suggested = f"tcp://{ip}:{RELAY_PORT}"
    running = relay_running_locally()

    print()
    print("  Online mode routes the phone through a relay server so it can")
    print("  reach this desktop from any network (end-to-end encrypted).")
    print()
    print(f"  This machine's LAN address: {ip}")
    if running:
        print(f"  A relay appears to be RUNNING locally on port {RELAY_PORT}.")
    print()
    print("  Relay options:")
    print(f"   [1] This machine  -  {suggested}")
    print("       Phones on this Wi-Fi can use it immediately. For other")
    print("       networks, forward port " + str(RELAY_PORT) + " on your router")
    print("       (then use your public IP) or use option 2 later.")
    print("   [2] A public server you own (VPS) - enter host:port yourself.")
    print("       Works from any network with no router changes. Run the")
    print("       relay there: python -m vma_relay.server --host 0.0.0.0 \\")
    print(f"                     --port {RELAY_PORT} --reg-token <token>")
    print()
    choice = input("  Choose 1, 2, or Enter to skip online mode: ").strip()
    if choice == "1":
        token = secrets.token_urlsafe(16)
        persist(suggested, token)
        # repo root = desktop/ ..
        root = Path(__file__).resolve().parent.parent.parent
        bat = write_relay_launcher(root, token)
        print()
        print(f"  Saved relay {suggested} (token stored in config.toml).")
        print("  The desktop app hosts this relay AUTOMATICALLY while it runs —")
        print("  no separate relay window needed. (run_relay.bat was also created")
        print("  in case you ever want to run the relay standalone.)")
        return True
    if choice == "2":
        url = input("  Relay address (host:port or tcp://host:port): ").strip()
        if not url:
            print("  Skipped — configure any time from the dashboard.")
            return False
        if "://" not in url:
            url = f"tcp://{url}"
        token = input("  Registration token (Enter to keep current): ").strip()
        persist(url, token or None)
        print(f"  Saved relay {url}.")
        return True
    print("  Skipped — configure any time from the dashboard.")
    return False


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return 0 if relay_configured() else 1
    if "--set" in argv:
        rest = argv[argv.index("--set") + 1:]
        if not rest:
            print("usage: python -m vma.set_relay --set URL [TOKEN]", file=sys.stderr)
            return 2
        url = rest[0]
        token = rest[1] if len(rest) > 1 else None
        persist(url, token)
        print(f"relay settings saved to config.toml ({url})")
        return 0
    if "--wizard" in argv:
        return 0 if wizard() else 1
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
